// Generated by gencpp from file your_package/id.msg
// DO NOT EDIT!


#ifndef YOUR_PACKAGE_MESSAGE_ID_H
#define YOUR_PACKAGE_MESSAGE_ID_H

#include <ros/service_traits.h>


#include <your_package/idRequest.h>
#include <your_package/idResponse.h>


namespace your_package
{

struct id
{

typedef idRequest Request;
typedef idResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct id
} // namespace your_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::your_package::id > {
  static const char* value()
  {
    return "08624c9d6f9820cb95f5c05a5c49c525";
  }

  static const char* value(const ::your_package::id&) { return value(); }
};

template<>
struct DataType< ::your_package::id > {
  static const char* value()
  {
    return "your_package/id";
  }

  static const char* value(const ::your_package::id&) { return value(); }
};


// service_traits::MD5Sum< ::your_package::idRequest> should match
// service_traits::MD5Sum< ::your_package::id >
template<>
struct MD5Sum< ::your_package::idRequest>
{
  static const char* value()
  {
    return MD5Sum< ::your_package::id >::value();
  }
  static const char* value(const ::your_package::idRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::your_package::idRequest> should match
// service_traits::DataType< ::your_package::id >
template<>
struct DataType< ::your_package::idRequest>
{
  static const char* value()
  {
    return DataType< ::your_package::id >::value();
  }
  static const char* value(const ::your_package::idRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::your_package::idResponse> should match
// service_traits::MD5Sum< ::your_package::id >
template<>
struct MD5Sum< ::your_package::idResponse>
{
  static const char* value()
  {
    return MD5Sum< ::your_package::id >::value();
  }
  static const char* value(const ::your_package::idResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::your_package::idResponse> should match
// service_traits::DataType< ::your_package::id >
template<>
struct DataType< ::your_package::idResponse>
{
  static const char* value()
  {
    return DataType< ::your_package::id >::value();
  }
  static const char* value(const ::your_package::idResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // YOUR_PACKAGE_MESSAGE_ID_H
